window.__GL=(window.__GL||[]);
window.__GL.push.apply(window.__GL, [
"(() => {",
"  'use strict';",
"  const TOTAL_SHOTS = 5;",
"  const canvas = document.getElementById('game');",
"  const ctx = canvas.getContext('2d');",
"  const hudShot = document.getElementById('shotLabel');",
"  const hudScore = document.getElementById('scoreValue');",
"  const hint = document.getElementById('hint');",
"  const banner = document.getElementById('banner');",
"  const startOverlay = document.getElementById('start');",
"  const endOverlay = document.getElementById('end');",
"  const endTitle = document.getElementById('endTitle');",
"  const endScore = document.getElementById('endScore');",
"  const endFlavor = document.getElementById('endFlavor');",
"  const muteBtn = document.getElementById('muteBtn');",
"  let W = 390;",
"  let H = 844;",
"  let muted = false;",
"  let audioCtx = null;",
"  const state = {",
"    phase: 'title', // title | aim | flying | resolve | between | end",
"    shot: 1,",
"    goals: 0,",
"    bg: null,",
"    ball: null,",
"    keeper: null,",
"    trail: [],",
"    particles: [],",
"    resultTimer: 0,",
"    lastTs: 0,",
"    pointerId: null,",
"    drag: null,",
"    message: '',",
"  };",
"  const field = {",
"    goalY: 0.38,",
"    goalLeft: 0.18,",
"    goalRight: 0.82,",
"    goalTop: 0.22,",
"    goalBottom: 0.42,",
"    ballStartX: 0.5,",
"    ballStartY: 0.78,",
"  };",
"  function resize() {",
"    const app = document.getElementById('app');",
"    const rect = app.getBoundingClientRect();",
"    const dpr = Math.min(window.devicePixelRatio || 1, 2.5);",
"    W = Math.max(320, Math.floor(rect.width));",
"    H = Math.max(480, Math.floor(rect.height));",
"    canvas.width = Math.floor(W * dpr);",
"    canvas.height = Math.floor(H * dpr);",
"    canvas.style.width = W + 'px';",
"    canvas.style.height = H + 'px';",
"    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);",
"  }",
"  function loadBg() {",
"    return new Promise((resolve) => {",
"      const img = new Image();",
"      img.onload = () => {",
"        state.bg = img;",
"        resolve();",
"      };"
]);
