window.__GL=(window.__GL||[]);
window.__GL.push.apply(window.__GL, [
"      img.onerror = () => resolve();",
"      if (window.STADIUM_BG) {",
"        img.src = window.STADIUM_BG;",
"      } else {",
"        img.src = 'stadium.jpg';",
"      }",
"    });",
"  }",
"  function resetBall() {",
"    state.ball = {",
"      x: field.ballStartX * W,",
"      y: field.ballStartY * H,",
"      vx: 0,",
"      vy: 0,",
"      r: Math.max(18, W * 0.055),",
"      z: 0,",
"      vz: 0,",
"      scale: 1,",
"      flying: false,",
"      spinning: 0,",
"    };",
"    state.trail = [];",
"  }",
"  function resetKeeper() {",
"    const gx = W * 0.5;",
"    const gy = H * field.goalBottom - 8;",
"    state.keeper = {",
"      x: gx,",
"      y: gy,",
"      homeX: gx,",
"      homeY: gy,",
"      w: W * 0.14,",
"      h: H * 0.12,",
"      diveX: 0,",
"      diveY: 0,",
"      t: 0,",
"      committed: false,",
"      diveDir: 0,",
"      diveHeight: 0,",
"      reactAt: 0,",
"      readBias: 0,",
"      limbPhase: 0,",
"      stretch: 0,",
"    };",
"  }",
"  function startMatch() {",
"    state.shot = 1;",
"    state.goals = 0;",
"    state.phase = 'aim';",
"    state.particles = [];",
"    resetBall();",
"    resetKeeper();",
"    updateHud();",
"    hint.classList.remove('hidden');",
"    hint.textContent = 'FLICK THE BALL';",
"    banner.classList.add('hidden');",
"    startOverlay.classList.add('hidden');",
"    endOverlay.classList.add('hidden');",
"    ensureAudio();",
"  }",
"  function updateHud() {",
"    hudShot.textContent = `SHOT ${Math.min(state.shot, TOTAL_SHOTS)} / ${TOTAL_SHOTS}`;"
]);
